### ISSUE TITLE
Write a plugin, hosted in the module, to modify the VCF details page

### ISSUE THREAD

**Issue by jctrotter** [BimberLab/DiscvrLabKeyModules#40]
Task 3

**Comment by bbimber** [comment]
## Background:

Starting with our demo session:
http://localhost:8080/labkey/jbrowse/home/jbrowse.view?session=Demo

Navigate to the coordinate:
1:118,884,813..118,884,813

Click that variant to load the details page:

![image](https://user-images.githubusercontent.com/7724863/119414966-7e541f00-bca5-11eb-8a8b-cac296179fcf.png)

You’ll see this shows a basic table that’s essentially rendering simple name/value pairs. This is showing the raw data, as provided by the VCF. There are many cases where we want to intercept rendering and show a more user-friendly version of the raw data. 

Compare this to the result of mGAP’s plugin:
 
![image](https://user-images.githubusercontent.com/7724863/119414985-8a3fe100-bca5-11eb-8747-c39199f81e4d.png)

There are several general differences:
1)	Instead of naively iterating every property, we know upfront what properties we care about. We only show those attributes the code defined ahead of time. 
2)	Also, instead of one ‘attributes’ section, they are grouped. 
3)	Specific attributes are given a custom renderer function. For example, the SnpEff raw data is this massive string. The JS code splits and parses that string. It then renders a user-friendly table instead of just the raw string. For the purposes of this task, we want to develop ‘hello world’-esque custom renders. 


## Specific Tasks:

1) Basic rendering:
- Using a plugin, override the rendering of a specific field, based on name, like 'MC'. 
- For this task, take the MC field, split on pipe, and render one line per chunk. The point is to verify we can do things like this.
- For the CLNREVSTAT field (which is multi-values), override the default behavior to render a table-thing (see screenshot), and render as a comma-delimited string

2) Grouping attributes:
- Our plugin should accept a config object that specifies what attributes to show and how to group them into sections. This should be an array of section definitions:
	[{name: ‘Predicted Function’, properties: ['AF_ESP', 'ALLELEID']},{name: ‘Regulatory Data’, properties: ['CLNDN', 'CLNVC']}]

- Each element in that array is rendered as a section (like the mGAP screenshot), with that title and those properties.

3) Bring these concepts together. Extend the grouping definitions to allow you to supply a custom renderer for each field. For example:

[
{name: ‘Predicted Function’, properties: ['AF_ESP', 'ALLELEID',{name: ‘MC’, renderer: XXXX}]},
{name: ‘Regulatory Data’, properties: ['CLNDN', {name: 'CLNVC', label: 'Clinical Variant']}
]

where the MC field is supplying extra config. We also want to be able to override the label. I dont know if this would take a whole new rendering function or if we can inject that more simply.
