### ISSUE TITLE
Further JSON config capabilities

### ISSUE THREAD

**Issue by jctrotter** [BimberLab/DiscvrLabKeyModules#41]
Task 4:
- Can our JSON config specify a default region to show?
- Can our JSON config specify a default set of tracks to show?

**Comment by bbimber** [comment]
This is basically a research task:

- Figure out what config is or isnt supported in the JSON.  I think you said there was a 'region' option, for example.

- Are there existing ways to provide this info on the URL, which react-lineage-genome-view already uses? for example if we had 'loc=XXXX' on the URL, would JB2 read and use this? JB1 did this, and it would make sense if JB2 replicated that.

The driving use case would be to be able to generate links to load the browser, already displaying a particular region (instead of taking like 4 clicks to get there).
